SECRET_KEY = 'set_your_secret_key'
SQLALCHEMY_DATABASE_URI = "mysql://root:root@localhost:3306/db_name"
SQLALCHEMY_TRACK_MODIFICATIONS = true
SQLALCHEMY_ECHO = false
UPLOAD_ROOT_DIR = "static/upload/"